# Конфигурация Nixpacks для Railway
# Этот файл обеспечивает стабильную работу с Python и pip

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip --break-system-packages",
    "python -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python bot/main.py"

# Переменные окружения для стабильности
[env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
