[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip --break-system-packages && pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "python bot/main.py"
