[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = ["python -m pip install --upgrade pip --break-system-packages", "python -m pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "python bot/main.py"
