[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["source /opt/venv/bin/activate && pip install --upgrade pip", "source /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "source /opt/venv/bin/activate && python bot/main.py"
