name: 🎭 Staging Deploy (PR Preview)

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: 🔍 PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3
    
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🧪 Quick tests
      run: |
        pip install pytest pytest-cov
        python -m pytest tests/ -v --maxfail=3
      env:
        BOT_TOKEN: test_token_1234567890:ABCdefGHIjklMNOpqrsTUVwxyz
        ADMIN_CHAT_ID: 123456789
        LOG_LEVEL: ERROR
    
    - name: ✅ PR validation passed
      run: echo "✅ PR готов к review"

  staging-info:
    name: 📢 Staging Deployment Info
    runs-on: ubuntu-latest
    needs: pr-validation
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3
    
    - name: 📊 PR Information
      run: |
        echo "🎭 Staging Deployment для PR #${{ github.event.pull_request.number }}"
        echo "📝 Title: ${{ github.event.pull_request.title }}"
        echo "👤 Author: ${{ github.event.pull_request.user.login }}"
        echo "🌿 Branch: ${{ github.head_ref }}"
        echo "📝 Commit: ${{ github.event.pull_request.head.sha }}"
    
    - name: 💡 Railway PR Deployment
      run: |
        echo "🚂 Railway PR Deployments:"
        echo ""
        echo "Для настройки автоматических PR deployments в Railway:"
        echo "1. Зайдите в Railway Dashboard → Project Settings"
        echo "2. Включите 'PR Deployments'"
        echo "3. Railway автоматически создаст preview для каждого PR"
        echo ""
        echo "После настройки каждый PR будет иметь свой staging URL!"

  comment-on-pr:
    name: 💬 Comment on PR
    runs-on: ubuntu-latest
    needs: pr-validation
    if: github.event.action == 'opened'
    
    steps:
    - name: 💬 Add PR comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.issue.number;
          const comment = `## 🎭 Staging Deployment
          
          ✅ PR validation прошла успешно!
          
          ### 🚂 Railway Preview Deployment
          
          После настройки Railway PR Deployments, здесь появится ссылка на staging окружение.
          
          **Настройка Railway PR Deployments:**
          1. Railway Dashboard → Project Settings
          2. Включите "PR Deployments"
          3. Railway автоматически создаст preview URL
          
          ### 📋 Checklist перед merge:
          - [ ] Все тесты проходят
          - [ ] Code review выполнен
          - [ ] Нет конфликтов с main
          - [ ] Документация обновлена (если требуется)
          - [ ] Покрытие кода ≥70%
          
          ---
          
          🤖 Автоматический комментарий от CI/CD`;
          
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: comment
          });

  security-check:
    name: 🔒 Security Check for PR
    runs-on: ubuntu-latest
    needs: pr-validation
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3
    
    - name: 🔍 Check for sensitive data
      run: |
        echo "🔍 Проверка на утечку секретов в PR..."
        
        # Проверка на хардкод секретов
        if git diff origin/main...HEAD | grep -iE "(password|secret|token|api_key|private_key)" | grep -v "BOT_TOKEN.*os.getenv" | grep -v "#"; then
          echo "⚠️ Возможная утечка секретов обнаружена!"
          echo "Проверьте изменения вручную"
        else
          echo "✅ Явных секретов не обнаружено"
        fi
      continue-on-error: true
    
    - name: 🔍 Check for .env files
      run: |
        if git diff origin/main...HEAD --name-only | grep -E "\.env$|\.env\."; then
          echo "❌ КРИТИЧНО: .env файл добавлен в PR!"
          exit 1
        else
          echo "✅ .env файлы не добавлены"
        fi

  coverage-diff:
    name: 📊 Coverage Comparison
    runs-on: ubuntu-latest
    needs: pr-validation
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 📦 Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: 📊 Generate coverage for PR
      run: |
        python -m pytest tests/ --cov=bot --cov-report=xml --cov-report=term
      env:
        BOT_TOKEN: test_token_1234567890:ABCdefGHIjklMNOpqrsTUVwxyz
        ADMIN_CHAT_ID: 123456789
        LOG_LEVEL: ERROR
      continue-on-error: true
    
    - name: 📈 Check coverage
      run: |
        python scripts/check_coverage.py || echo "⚠️ Coverage below threshold"
      continue-on-error: true

  deployment-summary:
    name: 📋 Deployment Summary
    runs-on: ubuntu-latest
    needs: [pr-validation, security-check, coverage-diff]
    if: always()
    
    steps:
    - name: 📊 Summary
      run: |
        echo "📋 Staging Deployment Summary"
        echo "=============================="
        echo ""
        echo "PR Validation: ${{ needs.pr-validation.result }}"
        echo "Security Check: ${{ needs.security-check.result }}"
        echo "Coverage Check: ${{ needs.coverage-diff.result }}"
        echo ""
        if [ "${{ needs.pr-validation.result }}" = "success" ]; then
          echo "✅ PR готов к review и merge!"
        else
          echo "❌ PR требует исправлений"
        fi

